const images = [
    { id: 1, src: 'images/dsc-6767.jpg', title: 'Pajarracos refrigerándose' },
    { id: 2, src: 'images/dsc-0090.jpg', title: 'Chisco descansando en un árbol' },
    { id: 3, src: 'images/dsc-0095.jpg', title: 'Chisco paseando por la tierra' },
    { id: 4, src: 'images/dsc-0096.jpg', title: 'El mismo Chisco mirando a la derecha' },
    { id: 5, src: 'images/dsc-0103.jpg', title: 'Un Chisco preparando el vuelo' },
    { id: 6, src: 'images/dsc-0109.jpg', title: 'Chisco mirando épicamente' },
    { id: 7, src: 'images/dsc-0116.jpg', title: 'Botón de oro mirando una hoja' },
    { id: 8, src: 'images/dsc-0118.jpg', title: 'Botón de oro posando para la cámara' },
    { id: 9, src: 'images/dsc-0122.jpg', title: 'Chisco farmeando aura' },
    { id: 10, src: 'images/dsc-0132.jpg', title: 'Dos Botones de oro pasándola bien' },
    { id: 11, src: 'images/dsc-0137.jpg', title: 'Botón de oro mirando pensativamente' },
    { id: 12, src: 'images/dsc-0145.jpg', title: 'Botón de oro orándole a diosito' },
    { id: 13, src: 'images/dsc-0155.jpg', title: 'Guardacaballo siendo el más capo' },
    { id: 14, src: 'images/dsc-0159.jpg', title: 'Guardacaballo pisando grass' },
    { id: 15, src: 'images/dsc-0161.jpg', title: 'Botones de oro chismeando en un árbol' },
    { id: 16, src: 'images/dsc-0163.jpg', title: 'Botones de oro chismeando en un árbol (cont.)' },
    { id: 17, src: 'images/dsc-0175.jpg', title: 'Guardacaballo chilleando en el agua' },
    { id: 18, src: 'images/dsc-0813.jpg', title: 'Chisco chisqueando' },
    { id: 19, src: 'images/dsc-0814.jpg', title: 'Chisco camuflado' },
    { id: 20, src: 'images/dsc-0826.jpg', title: 'Chisco (de cerca)' },
    { id: 21, src: 'images/dsc-0829.jpg', title: 'Chisco creyéndose Batman' },
];
