// `images` comes from images-data.js, generated by ./update-gallery.sh
// `metadata.json` is hand-edited: order/title/date/description per photo, keyed by filename slug.
let currentImageIndex = 0;

const REVEAL_STEP_MS = 30;
const REVEAL_MAX_DELAY_MS = 300;

function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str ?? '';
    return div.innerHTML;
}

function slugFromSrc(src) {
    return src.split('/').pop().replace(/\.[^.]+$/, '');
}

async function loadMetadata() {
    try {
        const res = await fetch('metadata.json');
        if (!res.ok) return {};
        return await res.json();
    } catch {
        return {};
    }
}

function applyMetadata(metadata) {
    images.forEach((img, index) => {
        const meta = metadata[slugFromSrc(img.src)] || {};
        if (meta.title) img.title = meta.title;
        img.date = meta.date || '';
        img.description = meta.description || '';
        img.order = meta.order !== undefined && meta.order !== null && meta.order !== ''
            ? Number(meta.order)
            : index + 1;
    });
    // order 0 hides a photo from the gallery entirely (see scripts/gallery.py load --order-by).
    // Mutate images in place rather than reassigning it — it's declared `const` in images-data.js.
    const visible = images.filter((img) => img.order !== 0);
    images.length = 0;
    images.push(...visible);
    images.sort((a, b) => a.order - b.order);
}

function renderGallery() {
    const gallery = document.getElementById('gallery');

    if (images.length === 0) {
        gallery.innerHTML = `
            <p class="gallery-empty">No photos yet. Add .NEF files to raw-photos/ and run ./update-gallery.sh</p>
        `;
        return;
    }

    gallery.innerHTML = images.map((img, index) => `
        <div class="gallery-item" onclick="openLightbox(${index})">
            <img src="${img.src}" alt="${escapeHtml(img.title)}">
            <div class="gallery-item-title">${escapeHtml(img.title)}</div>
        </div>
    `).join('');
}

// CSS column-count fills the first column completely (top to bottom)
// before starting the next one, so an item's position in `images` doesn't
// match its visual column. Staggering by that flat index made whichever
// column got the earlier indices finish revealing before the next column
// had even started, which read as the columns not being top-aligned.
// Stagger by each item's position within its own column instead, so every
// column starts cascading in from the top at the same time. Must run after
// every image has actually loaded (see waitForGalleryImages) — column
// membership depends on each image's real height, which isn't known yet
// right after the markup is inserted.
function applyRevealStagger() {
    const columns = new Map();
    document.querySelectorAll('.gallery-item').forEach((el) => {
        const left = Math.round(el.getBoundingClientRect().left);
        if (!columns.has(left)) columns.set(left, []);
        columns.get(left).push(el);
    });
    columns.forEach((items) => {
        items.sort((a, b) => a.getBoundingClientRect().top - b.getBoundingClientRect().top);
        items.forEach((el, i) => {
            el.style.setProperty('--reveal-delay', `${Math.min(i * REVEAL_STEP_MS, REVEAL_MAX_DELAY_MS)}ms`);
        });
    });
}

// Waits on the actual gallery <img> elements (not a duplicate fetch) so the
// grid can stay hidden until every photo is genuinely ready to paint.
function waitForGalleryImages() {
    const imgs = Array.from(document.querySelectorAll('.gallery-item img'));
    return Promise.all(imgs.map((el) => {
        if (el.complete) return Promise.resolve();
        return new Promise((resolve) => {
            el.addEventListener('load', resolve, { once: true });
            el.addEventListener('error', resolve, { once: true });
        });
    }));
}

function revealGallery() {
    document.getElementById('gallery').classList.add('is-ready');
}

function renderCaption(img) {
    const caption = document.getElementById('lightbox-caption');
    const parts = [];
    if (img.title) parts.push(`<div class="lightbox-caption-title">${escapeHtml(img.title)}</div>`);
    if (img.date) parts.push(`<div class="lightbox-caption-date">${escapeHtml(img.date)}</div>`);
    if (img.description) parts.push(`<div class="lightbox-caption-description">${escapeHtml(img.description)}</div>`);
    caption.innerHTML = parts.join('');
}

function openLightbox(index) {
    currentImageIndex = index;
    const lightbox = document.getElementById('lightbox');
    const img = document.getElementById('lightbox-img');
    img.src = images[index].src;
    img.alt = `Photo: ${images[index].title}`;
    renderCaption(images[index]);
    lightbox.classList.add('active');
    document.body.style.overflow = 'hidden';
    lightbox.focus();
}

function closeLightbox() {
    const lightbox = document.getElementById('lightbox');
    lightbox.classList.remove('active');
    document.body.style.overflow = 'auto';
}

function nextImage() {
    currentImageIndex = (currentImageIndex + 1) % images.length;
    const img = images[currentImageIndex];
    document.getElementById('lightbox-img').src = img.src;
    document.getElementById('lightbox-img').alt = `Photo: ${img.title}`;
    renderCaption(img);
}

function prevImage() {
    currentImageIndex = (currentImageIndex - 1 + images.length) % images.length;
    const img = images[currentImageIndex];
    document.getElementById('lightbox-img').src = img.src;
    document.getElementById('lightbox-img').alt = `Photo: ${img.title}`;
    renderCaption(img);
}

// Touch swipe support
let touchStartX = 0;
let touchEndX = 0;

document.addEventListener('touchstart', (e) => {
    if (document.getElementById('lightbox').classList.contains('active')) {
        touchStartX = e.changedTouches[0].screenX;
    }
}, false);

document.addEventListener('touchend', (e) => {
    if (document.getElementById('lightbox').classList.contains('active')) {
        touchEndX = e.changedTouches[0].screenX;
        if (touchStartX - touchEndX > 50) nextImage();
        if (touchEndX - touchStartX > 50) prevImage();
    }
}, false);

// Keyboard navigation
document.addEventListener('keydown', (e) => {
    if (document.getElementById('lightbox').classList.contains('active')) {
        if (e.key === 'ArrowRight') nextImage();
        if (e.key === 'ArrowLeft') prevImage();
        if (e.key === 'Escape') closeLightbox();
    }
});

// Close on background click. The layout wrappers between #lightbox and the
// photo (.lightbox-content, .lightbox-image-row) have their own box area —
// e.g. the image's padding, or the gap left/right of a narrow photo — so a
// click there lands on the wrapper, not #lightbox itself. Treat anything
// that isn't the photo, a control, or the caption as background instead.
document.getElementById('lightbox').addEventListener('click', (e) => {
    if (e.target.closest('#lightbox-img, .lightbox-close, .lightbox-nav, .lightbox-caption')) return;
    closeLightbox();
});

// Initialize: merge metadata, render markup, wait for every photo to be
// ready, then reveal the grid in one staggered cascade.
(async function init() {
    const metadata = await loadMetadata();
    applyMetadata(metadata);
    renderGallery();

    if (images.length > 0) {
        await waitForGalleryImages();
        applyRevealStagger();
    }
    revealGallery();
})();
