// `images` comes from images-data.js, generated by ./update-gallery.sh
// `metadata.json` is hand-edited: title/date/description per photo, keyed by filename slug.
let currentImageIndex = 0;

const REVEAL_STEP_MS = 30;
const REVEAL_MAX_DELAY_MS = 300;

function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str ?? '';
    return div.innerHTML;
}

function slugFromSrc(src) {
    return src.split('/').pop().replace(/\.[^.]+$/, '');
}

async function loadMetadata() {
    try {
        const res = await fetch('metadata.json');
        if (!res.ok) return {};
        return await res.json();
    } catch {
        return {};
    }
}

function applyMetadata(metadata) {
    images.forEach((img) => {
        const meta = metadata[slugFromSrc(img.src)] || {};
        if (meta.title) img.title = meta.title;
        img.date = meta.date || '';
        img.description = meta.description || '';
    });
}

function renderGallery() {
    const gallery = document.getElementById('gallery');

    if (images.length === 0) {
        gallery.innerHTML = `
            <p class="gallery-empty">No photos yet. Add .NEF files to raw-photos/ and run ./update-gallery.sh</p>
        `;
        return;
    }

    gallery.innerHTML = images.map((img, index) => `
        <div class="gallery-item" style="--reveal-delay: ${Math.min(index * REVEAL_STEP_MS, REVEAL_MAX_DELAY_MS)}ms" onclick="openLightbox(${index})">
            <img src="${img.src}" alt="${escapeHtml(img.title)}">
            <div class="gallery-item-title">${escapeHtml(img.title)}</div>
        </div>
    `).join('');
}

// Waits on the actual gallery <img> elements (not a duplicate fetch) so the
// grid can stay hidden until every photo is genuinely ready to paint.
function waitForGalleryImages() {
    const imgs = Array.from(document.querySelectorAll('.gallery-item img'));
    return Promise.all(imgs.map((el) => {
        if (el.complete) return Promise.resolve();
        return new Promise((resolve) => {
            el.addEventListener('load', resolve, { once: true });
            el.addEventListener('error', resolve, { once: true });
        });
    }));
}

function revealGallery() {
    document.getElementById('gallery').classList.add('is-ready');
}

function renderCaption(img) {
    const caption = document.getElementById('lightbox-caption');
    const parts = [];
    if (img.title) parts.push(`<div class="lightbox-caption-title">${escapeHtml(img.title)}</div>`);
    if (img.date) parts.push(`<div class="lightbox-caption-date">${escapeHtml(img.date)}</div>`);
    if (img.description) parts.push(`<div class="lightbox-caption-description">${escapeHtml(img.description)}</div>`);
    caption.innerHTML = parts.join('');
}

function openLightbox(index) {
    currentImageIndex = index;
    const lightbox = document.getElementById('lightbox');
    const img = document.getElementById('lightbox-img');
    img.src = images[index].src;
    renderCaption(images[index]);
    lightbox.classList.add('active');
    document.body.style.overflow = 'hidden';
}

function closeLightbox() {
    const lightbox = document.getElementById('lightbox');
    lightbox.classList.remove('active');
    document.body.style.overflow = 'auto';
}

function nextImage() {
    currentImageIndex = (currentImageIndex + 1) % images.length;
    const img = images[currentImageIndex];
    document.getElementById('lightbox-img').src = img.src;
    renderCaption(img);
}

function prevImage() {
    currentImageIndex = (currentImageIndex - 1 + images.length) % images.length;
    const img = images[currentImageIndex];
    document.getElementById('lightbox-img').src = img.src;
    renderCaption(img);
}

// Keyboard navigation
document.addEventListener('keydown', (e) => {
    if (document.getElementById('lightbox').classList.contains('active')) {
        if (e.key === 'ArrowRight') nextImage();
        if (e.key === 'ArrowLeft') prevImage();
        if (e.key === 'Escape') closeLightbox();
    }
});

// Close on background click. The layout wrappers between #lightbox and the
// photo (.lightbox-content, .lightbox-image-row) have their own box area —
// e.g. the image's padding, or the gap left/right of a narrow photo — so a
// click there lands on the wrapper, not #lightbox itself. Treat anything
// that isn't the photo, a control, or the caption as background instead.
document.getElementById('lightbox').addEventListener('click', (e) => {
    if (e.target.closest('#lightbox-img, .lightbox-close, .lightbox-nav, .lightbox-caption')) return;
    closeLightbox();
});

// Initialize: merge metadata, render markup, wait for every photo to be
// ready, then reveal the grid in one staggered cascade.
(async function init() {
    const metadata = await loadMetadata();
    applyMetadata(metadata);
    renderGallery();

    if (images.length > 0) {
        await waitForGalleryImages();
    }
    revealGallery();
})();
