#!/usr/bin/env python3
"""Generates the static English pages and sitemap.xml.

The Spanish pages are the hand-edited sources and carry both languages as
<span data-i18n-es> / <span data-i18n-en hidden> pairs. Search engines can't
index text that only appears after a JS toggle, so this script derives a real
English URL for each page (en/index.html, en/resume/index.html) with the
Spanish text removed, the English text visible, and language-specific
title/description/canonical/social tags. Re-run after editing a source page:

    python3 tools/resume/build.py ...   # regenerates the resume source page + PDFs
    python3 tools/seo/build.py          # regenerates /en/ pages + sitemap.xml

No third-party dependencies.
"""
import datetime
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
SITE = "https://www.mariocornejo.com"
GENERATED = "<!-- Generated by tools/seo/build.py from {src} — edit the source, not this file. -->"

# --- English pages -----------------------------------------------------------
PAGES = [
    {
        "src": "index.html",
        "out": "en/index.html",
        "base": "/",  # directory the source page lives in, for relative URLs
        "url": f"{SITE}/en/",
        "title": "Mario Cornejo — Business Analyst in Lima, Peru",
        "description": "Business Analyst in Lima, Peru: process optimization, SQL, Python and reporting automation. Native English and Spanish speaker; U.S. and Peruvian citizen.",
        "social_title": "Mario Cornejo — Business Analyst in Lima, Peru",
        "social_description": "Process optimization, SQL, Python and reporting automation. Native English–Spanish bilingual.",
        "links": {"/media/documents/resume/index.html": "/en/resume/"},
        "alts": {
            "Retrato de Mario Cornejo": "Portrait of Mario Cornejo",
            "Foto de un ave de la galería Pajaritos": "Photo of a bird from the Pajaritos gallery",
            "Diagrama del flujo Excel Power Query a SQL y Python; ciclo de QA de más de 4 horas a unos 25 minutos": "Diagram of the Excel Power Query to SQL and Python workflow; QA cycle cut from over 4 hours to about 25 minutes",
            "Tablero de raspado Garabatos con un dibujo de un sol y olas en colores de arcoíris": "Garabatos scratch board with a sun and waves drawn in rainbow colors",
            "Nuevo: Garabatos": "New: Garabatos",
            "Juego GoGoLogo: dibujos de colores como nave y enemigos en un shooter arcade": "GoGoLogo game: colorful drawings as the ship and enemies in an arcade shooter",
        },
    },
    {
        "src": "media/documents/resume/index.html",
        "out": "en/resume/index.html",
        "base": "/media/documents/resume/",
        "url": f"{SITE}/en/resume/",
        "title": "Resume — Mario Cornejo",
        "description": "Resume of Mario Roy Cornejo Bellido: Business Analyst in Lima, Peru. SQL, Python and reporting automation. Native English–Spanish bilingual.",
        "social_title": "Resume — Mario Cornejo",
        "social_description": "Business Analyst in Lima, Peru. SQL, Python, reporting automation. Native English–Spanish bilingual.",
        "links": {},
        "alts": {},
    },
]

# --- Sitemap -----------------------------------------------------------------
# (path, source files whose last change dates it, {hreflang: path} alternates)
SITEMAP = [
    ("/", ["index.html", "script.js", "styles.css"], {"es": "/", "en": "/en/", "x-default": "/"}),
    ("/en/", ["index.html", "script.js", "styles.css"], {"es": "/", "en": "/en/", "x-default": "/"}),
    ("/media/documents/resume/index.html", ["media/documents/resume/index.html", "media/documents/resume.pdf"],
     {"es": "/media/documents/resume/index.html", "en": "/en/resume/", "x-default": "/media/documents/resume/index.html"}),
    ("/en/resume/", ["media/documents/resume/index.html", "media/documents/resume-en.pdf"],
     {"es": "/media/documents/resume/index.html", "en": "/en/resume/", "x-default": "/media/documents/resume/index.html"}),
    ("/unicanal-demo/", ["unicanal-demo/index.html", "unicanal-demo/demo.js"], {}),
    ("/garabatos/index.html", ["garabatos/index.html", "garabatos/script.js"], {}),
    ("/gallery/pajaritos/", ["gallery/pajaritos/index.html", "gallery/pajaritos/metadata.json"], {}),
    ("/gallery/garabatos/", ["gallery/garabatos/index.html", "gallery/garabatos/script.js"], {}),
    ("/gallery/garabatos-fotos/", ["gallery/garabatos-fotos/index.html", "gallery/garabatos-fotos/script.js"], {}),
    ("/gogologo/", ["gogologo/index.html"], {}),
]


def sub1(pattern, repl, text, what):
    new, n = re.subn(pattern, lambda m: repl, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"build.py: could not find {what} to replace")
    return new


def set_meta(html, attr, key, content):
    return sub1(rf'<meta {attr}="{re.escape(key)}" content="[^"]*">', f'<meta {attr}="{key}" content="{content}">', html, f"{key} meta")


def remove_by_attr(html, attr):
    """Remove every element carrying `attr`, matching nested same-name tags."""
    open_re = re.compile(rf"<(\w+)\b[^>]*\s{re.escape(attr)}(?=[\s>=])[^>]*>")
    while True:
        m = open_re.search(html)
        if not m:
            return html
        tag, depth, pos = m.group(1), 1, m.end()
        tag_re = re.compile(rf"<(/?){tag}\b[^>]*>")
        while depth:
            t = tag_re.search(html, pos)
            if not t:
                raise SystemExit(f"build.py: unbalanced <{tag}> while removing {attr}")
            depth += -1 if t.group(1) else 1
            pos = t.end()
        html = html[:m.start()] + html[pos:]


def unhide_by_attr(html, attr):
    def fix(m):
        return re.sub(r"\s+hidden(?=[\s>])", "", m.group(0))
    return re.sub(rf"<\w+\b[^>]*\s{re.escape(attr)}(?=[\s>=])[^>]*>", fix, html)


def absolutize(html, base):
    def fix(m):
        attr, quote, val = m.group(1), m.group(2), m.group(3)
        if re.match(r"(/|#|[a-z][a-z0-9+.-]*:|\$\{)", val, re.I):
            return m.group(0)
        return f"{attr}={quote}{base}{val}{quote}"
    return re.sub(r'\b(href|src)=(["\'])([^"\']*)\2', fix, html)


def build_en(page):
    html = (ROOT / page["src"]).read_text()
    html = remove_by_attr(html, "data-i18n-es")
    html = unhide_by_attr(html, "data-i18n-en")
    html = sub1(r'<html lang="[^"]*"( data-lang="[^"]*")?', '<html lang="en" data-lang="en" data-lang-fixed', html, "<html>")
    html = re.sub(r"(<!DOCTYPE html>|<!doctype html>)", lambda m: m.group(1) + "\n" + GENERATED.format(src=page["src"]), html, count=1)
    html = sub1(r"<title>.*?</title>", f"<title>{page['title']}</title>", html, "<title>")
    html = set_meta(html, "name", "description", page["description"])
    html = sub1(r'<link rel="canonical" href="[^"]*">', f'<link rel="canonical" href="{page["url"]}">', html, "canonical")
    for key, val in (("og:title", page["social_title"]), ("og:description", page["social_description"]), ("og:url", page["url"])):
        html = set_meta(html, "property", key, val)
    html = set_meta(html, "property", "og:locale", "en_US")
    html = sub1(r'<meta property="og:locale:alternate" content="[^"]*">', '<meta property="og:locale:alternate" content="es_PE">', html, "og:locale:alternate")
    html = set_meta(html, "name", "twitter:title", page["social_title"])
    html = set_meta(html, "name", "twitter:description", page["social_description"])
    for old, new in page["alts"].items():
        if old not in html:
            raise SystemExit(f"build.py: alt/aria text not found: {old[:50]}")
        html = html.replace(f'"{old}"', f'"{new}"')
    for old, new in page["links"].items():
        html = html.replace(f'href="{old}"', f'href="{new}"')
    html = html.replace('"inLanguage": "es"', '"inLanguage": "en"')
    html = absolutize(html, page["base"])
    out = ROOT / page["out"]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    print("wrote", page["out"])


def lastmod(files):
    """Most recent commit date of the files; today if any has uncommitted changes."""
    paths = [f for f in files if (ROOT / f).exists()]
    dirty = subprocess.run(["git", "status", "--porcelain", "--", *paths], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    if dirty:
        return datetime.date.today().isoformat()
    out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", *paths], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    return out or datetime.date.today().isoformat()


def build_sitemap():
    # Generated pages count as dirty until committed, so date from their sources.
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    for path, files, alts in SITEMAP:
        lines += ["  <url>", f"    <loc>{SITE}{path}</loc>", f"    <lastmod>{lastmod(files)}</lastmod>"]
        for lang, p in alts.items():
            lines.append(f'    <xhtml:link rel="alternate" hreflang="{lang}" href="{SITE}{p}"/>')
        lines.append("  </url>")
    lines.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n")
    print("wrote sitemap.xml")


if __name__ == "__main__":
    for page in PAGES:
        build_en(page)
    build_sitemap()
